CREATE TABLE order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    product_id   BIGINT                                  NOT NULL,
    sku          VARCHAR(100)                            NOT NULL,
    product_name VARCHAR(200)                            NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    unit_price   DECIMAL(10, 2)                          NOT NULL,
    subtotal     DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    total_amount DECIMAL(10, 2)                          NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);