CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku         VARCHAR(100)                            NOT NULL,
    name        VARCHAR(200)                            NOT NULL,
    description VARCHAR(500),
    price       DECIMAL(10, 2)                          NOT NULL,
    quantity    INTEGER                                 NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT uc_products_sku UNIQUE (sku);

CREATE UNIQUE INDEX idx_sku ON products (sku);