CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT                                  NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    amount         DECIMAL(10, 2)                          NOT NULL,
    status         VARCHAR(20)                             NOT NULL,
    payment_method VARCHAR(20)                             NOT NULL,
    transaction_id VARCHAR(100),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_transactionid UNIQUE (transaction_id);

CREATE UNIQUE INDEX idx_transaction_id ON payments (transaction_id);